name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Ruff
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  
  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install uv
        run: pip install uv
      - name: Install package
        run: uv pip install --system -e .[test]
      - name: Run Tests
        run: python -m pytest
